import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Monoton, Tilt_Neon, Orbitron } from 'next/font/google';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const monoton = Monoton({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-monoton',
});
const tiltNeon = Tilt_Neon({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-tilt-neon',
});
const orbitron = Orbitron({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-orbitron',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${monoton.variable} ${tiltNeon.variable} ${orbitron.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
